# Generated by Django 5.1.7 on 2025-03-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('course_created', 'Course Created'), ('course_updated', 'Course Updated'), ('course_deleted', 'Course Deleted'), ('lesson_created', 'Lesson Created'), ('lesson_updated', 'Lesson Updated'), ('lesson_deleted', 'Lesson Deleted')], max_length=50, null=True),
        ),
    ]
