# Generated by Django 5.1.7 on 2025-03-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
