# Generated by Django 5.1.7 on 2025-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_instructor_delete_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the course', null=True, upload_to='course_covers/'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Price of the course', max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
